name: Update Snapshots on Comment
on:
  issue_comment:
    types: [created]

jobs:
  update-snapshots:
    name: Update Snapshots
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        node-version: [20]
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/approve-snapshots')

    steps:
      - name: Get branch of PR
        uses: xt0rted/pull-request-comment-branch@4d0b1387dddf780342553efbddb07489137a9159
        id: comment-branch
      - name: Checkout PR branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Comment action started
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6
        with:
          message: |
            ### Updating snapshots. Click [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) to see the status.

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Restore Turborepo cache
        uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-node-${{ matrix.node-version }}
      - name: Build packages
        run: pnpm build:packages
      - name: Get Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(npx playwright --version | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"
      - name: Playwright binary cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
      - name: Install Playwright browsers
        run: npx playwright install
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Install Playwright dependencies
        run: npx playwright install-deps
      - name: Start HTML server
        run: pnpm --filter @scalar-examples/cdn-api-reference dev &
      - name: Run E2E tests (jsdelivr)
        run: |
          CI=1 pnpm test:e2e:jsdelivr --update-snapshots
      - name: Commit and push updated snapshots
        uses: stefanzweifel/git-auto-commit-action@050015d40644de3e8d2365687c1fbc235352bcff
        with:
          commit_message: 'Update e2e snapshots'
      - name: Comment success
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6
        with:
          message: |
            ### 🎉 Successfully updated and committed Playwright snapshots! 🎉
